#dog 품종 정보 데이터
insert into dogkind values('치와와','소형견',2.7);
insert into dogkind values('요크셔테리어','소형견',2.7);
insert into dogkind values('토이 푸들','소형견',3);
insert into dogkind values('말티즈','소형견',3.2);
insert into dogkind values('포메라니안','소형견',3.2);
insert into dogkind values('미니어쳐 닥스훈트','소형견',4.8);
insert into dogkind values('비숑프리제','소형견',5.5);
insert into dogkind values('파피용','소형견',5.5);
insert into dogkind values('웨스티','소형견',6);
insert into dogkind values('페키니즈','소형견',6.5);
insert into dogkind values('시츄','소형견',7);
insert into dogkind values('미니어처 푸들','소형견',7);
insert into dogkind values('라사 압소','소형견',7);
insert into dogkind values('캐벌리어킹찰스 스파니엘','소형견',8);
insert into dogkind values('폭스 테리어','소형견',8);
insert into dogkind values('퍼그','소형견',8.5);
insert into dogkind values('스카치 테리어','소형견',9.5);
insert into dogkind values('미니어쳐 슈나우저','소형견',10);
insert into dogkind values('스탠더드 닥스훈트','소형견',10);
insert into dogkind values('셔틀랜드 십독','소형견',10);
insert into dogkind values('베들링턴 테리어','소형견',10);
insert into dogkind values('잉글리쉬 코커스파니엘','중형견',11);
insert into dogkind values('아메리칸 코커스파니엘','중형견',11);
insert into dogkind values('보스턴 테리어','중형견',11);
insert into dogkind values('비글','중형견',12);
insert into dogkind values('웨일스 코기','중형견',13);
insert into dogkind values('진돗개','중형견',19);
insert into dogkind values('차우차우','중형견',23);
insert into dogkind values('아프간 하운드','중형견',23);
insert into dogkind values('시베리안 허스키','중형견',23);
insert into dogkind values('불독','중형견',23);
insert into dogkind values('풍산개','중형견',23);
insert into dogkind values('삽살개','중형견',24);
insert into dogkind values('비어디드 콜리','중형견',25);
insert into dogkind values('사모예드','중형견',25);
insert into dogkind values('불테리어','중형견',25);
insert into dogkind values('스탠다드 푸들','중형견',25);
insert into dogkind values('달마시안','중형견',25);
insert into dogkind values('에어데일 테리어','중형견',25);
insert into dogkind values('샤페이','중형견',25);
insert into dogkind values('복서','중형견',27);
insert into dogkind values('아이리시 세터','중형견',27);
insert into dogkind values('콜리','대형견',29);
insert into dogkind values('잉글리시 포인터','대형견',29);
insert into dogkind values('그레이 하운드','대형견',29);
insert into dogkind values('살루키','대형견',29);
insert into dogkind values('올드 잉글리쉬십독','대형견',30);
insert into dogkind values('저먼 셰퍼드','대형견',31);
insert into dogkind values('도브르만 핀셔','대형견',32);
insert into dogkind values('골든 리트리버','대형견',32);
insert into dogkind values('래브라도 리트리버','대형견',32);
insert into dogkind values('아키타','대형견',34);
insert into dogkind values('알래스칸 말라뮤트','대형견',39);
insert into dogkind values('로트 바일러','대형견',39);
insert into dogkind values('보르조이','대형견',41);
insert into dogkind values('버니즈 마운틴 독','대형견',44);
insert into dogkind values('블러드 하운드','대형견',45);
insert into dogkind values('마스티프','대형견',50);
insert into dogkind values('그레이트 피레니스','대형견',52);
insert into dogkind values('뉴 펀들랜드','대형견',54);
insert into dogkind values('그레이트 데인','대형견',59);
insert into dogkind values('기타 소형견','소형견',8);
insert into dogkind values('기타 중형견','중형견',24);
insert into dogkind values('기타 대형견','대형견',35);

